name: 构建二进制并一起发布到npm


on:
  workflow_dispatch: # 手动触发
    inputs:
      job:
        description: "任务类型"
        required: true
        default: build
        type: string

jobs:
  build:
    if: ${{ github.event.inputs.job == 'build'  || github.event.inputs.job == 'push' }}
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
#          cache: "npm"

      - name: Install dev dependencies
        run: npm install

      - name: Build native module
        run: npx prebuildify --napi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: prebuilt-${{ runner.os }}
          path: prebuilds/

  release:
    if: ${{ github.event.inputs.job == 'push' }}
    name: Release Prebuilt Binaries
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: prebuilt-Windows
          path: prebuilds

      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: prebuilt-Linux
          path: prebuilds

      - name: Publish to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: |
            prebuilds/windows/*
            prebuilds/linux/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
